22 modele decentralise
ub-mmi-but/git-101 pull request #55
Opened 2023-09-12 09:58 UTC by lorenzo-bravard

2023-09-21 09:35 UTC, lorenzo-bravard commented
Closes #22

2023-09-21 09:36 UTC, Xeone971 requested changes
.

2023-09-21 09:36 UTC, Xeone971 commented on docs/modeleDecentralise.md
> +
Modele de quoi ? Peux etre précisé ce que c'est

2023-09-21 09:36 UTC, Xeone971 commented on docs/modeleDecentralise.md
> +| - Plus rapide  | - Plus complexe |
appyuyer le point du rapide avec un ex ou plusiuers +

2023-09-21 09:36 UTC, Xeone971 commented on docs/modeleDecentralise.md
> +
Je comprend pas pq c la ?

2023-09-21 09:56 UTC, lorenzo-bravard commented on docs/modeleDecentralise.md
> +
Il faut lire mon reuf

2023-09-21 09:56 UTC, lorenzo-bravard commented on docs/modeleDecentralise.md
> +| - Plus rapide  | - Plus complexe |
pourquoi ???????

2023-09-21 09:56 UTC, lorenzo-bravard commented on docs/modeleDecentralise.md
> +
c'était dans l'issue

2023-09-28 06:48 UTC, Xeone971 approved these changes

2023-10-03 06:53 UTC, LeGrano approved these changes

2023-10-03 06:54 UTC, merged