refactor: modification de l'arborescance des fichiers et du menu en front
ub-mmi-but/git-101 pull request #65
Opened 2023-09-28 09:38 UTC by XELAmp4

2023-09-28 09:46 UTC, Xeone971 requested changes
Modif route images

2023-09-28 09:46 UTC, Xeone971 commented on docs/1. Introduction/git.md
ok

2023-09-28 09:46 UTC, Xeone971 commented on docs/1. Introduction/github.md
Pas convaincu par les espaces

2023-10-03 07:40 UTC, JosephJoeJakson approved these changes
Tout est OK

2023-10-03 07:41 UTC, merged